

services:

  app:
    build:
      context: .

    container_name: node_app

    ports:
      - "5000:5000"

    environment:
      MONGO_URL: mongodb://mongo:27017/dockerapp

    depends_on:
      - mongo


  mongo:

    image: mongo:latest

    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db


volumes:

  mongo-data: